-- MySQL Script generated by MySQL Workbench
-- 2016年10月11日 星期二 23时21分26秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MagicBirdStudio_RBAC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MagicBirdStudio_RBAC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MagicBirdStudio_RBAC` DEFAULT CHARACTER SET utf8 ;
USE `MagicBirdStudio_RBAC` ;

-- -----------------------------------------------------
-- Table `MagicBirdStudio_RBAC`.`AccountInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagicBirdStudio_RBAC`.`AccountInfo` (
  `UserID` VARCHAR(16) NOT NULL COMMENT '用户ＩＤ(工号)',
  `UserName` VARCHAR(45) NOT NULL COMMENT '员工姓名',
  `Birthday` DATETIME NULL,
  `Telephone` VARCHAR(20) NOT NULL,
  `E-Mail` VARCHAR(45) NULL,
  `JobLevel` VARCHAR(45) NOT NULL COMMENT '记录员工职务\n如： \nXXX 部门  XXX 班组 XX(职务)\nXXX 部门 XX(职务)',
  `EntryTime` DATETIME NOT NULL COMMENT '入职时间',
  `isService` TINYINT(1) NOT NULL COMMENT '是否在职',
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB
COMMENT = '员工基本信息登记表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
