//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicBirdStudio_RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountinfo
    {
        public accountinfo()
        {
            this.userauth = new HashSet<userauth>();
        }
    
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Telephone { get; set; }
        public string E_Mail { get; set; }
        public string JobLevel { get; set; }
        public System.DateTime EntryTime { get; set; }
        public bool isService { get; set; }
    
        public virtual groupmanager groupmanager { get; set; }
        public virtual ICollection<userauth> userauth { get; set; }
    }
}
