//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicBirdStudio_RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupmanager
    {
        public groupmanager()
        {
            this.accountinfoes = new HashSet<accountinfo>();
        }
    
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
    
        public virtual roleinfo roleinfo { get; set; }
        public virtual ICollection<accountinfo> accountinfoes { get; set; }
    }
}
