//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicBirdStudio_RBAC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagicBirdStudio_RBACContainer : DbContext
    {
        public MagicBirdStudio_RBACContainer()
            : base("name=MagicBirdStudio_RBACContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accountinfo> accountinfoes { get; set; }
        public DbSet<groupmanager> groupmanagers { get; set; }
        public DbSet<menuinfo> menuinfoes { get; set; }
        public DbSet<permissioninfo> permissioninfoes { get; set; }
        public DbSet<roleinfo> roleinfoes { get; set; }
    }
}
