//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicBirdStudio_RBAC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class magicbirdstudiorbacEntities : DbContext
    {
        public magicbirdstudiorbacEntities()
            : base("name=magicbirdstudiorbacEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accountinfo> accountinfo { get; set; }
        public DbSet<groupmanager> groupmanager { get; set; }
        public DbSet<menuinfo> menuinfo { get; set; }
        public DbSet<permissioninfo> permissioninfo { get; set; }
        public DbSet<roleinfo> roleinfo { get; set; }
    }
}
