//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicBirdStudio_RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class permissioninfo
    {
        public permissioninfo()
        {
            this.menuinfoes = new HashSet<menuinfo>();
            this.roleinfoes = new HashSet<roleinfo>();
        }
    
        public int PermissionID { get; set; }
        public string PermissionName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<menuinfo> menuinfoes { get; set; }
        public virtual ICollection<roleinfo> roleinfoes { get; set; }
    }
}
