//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicBirdStudio_RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class userauth
    {
        public int ID { get; set; }
        // 用户ID,外键，指向AccountInfo
        public string UserID { get; set; }
        // 登录类型（手机号 邮箱 用户名）或第三方应用名称（微信 微博等）
        public string IdentityType { get; set; }
        // 标识（手机号 邮箱 用户名或第三方应用的唯一标识）
        public string Identifier { get; set; }
        // 密码凭证（站内的保存密码，站外的不保存或保存token）
        public string Credential { get; set; }
    
        public virtual accountinfo accountinfo { get; set; }
    }
}
