//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_ERP_INVENTORY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batchinformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public batchinformation()
        {
            this.incomeinformations = new HashSet<incomeinformation>();
            this.inspectinformations = new HashSet<inspectinformation>();
            this.pickstockinformations = new HashSet<pickstockinformation>();
            this.stockerrorinformations = new HashSet<stockerrorinformation>();
            this.stockinformations = new HashSet<stockinformation>();
            this.t_inspectreport = new HashSet<t_inspectreport>();
        }
    
        public string BatchID { get; set; }
        public string ComponentID { get; set; }
        public string BatchNum { get; set; }
        public string Unit { get; set; }
        public string Manufacturer { get; set; }
        public string Agent { get; set; }
        public string PurchaseID { get; set; }
        public string NowState { get; set; }
    
        public virtual componentinformation componentinformation { get; set; }
        public virtual purchasecontract purchasecontract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incomeinformation> incomeinformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inspectinformation> inspectinformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pickstockinformation> pickstockinformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stockerrorinformation> stockerrorinformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stockinformation> stockinformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_inspectreport> t_inspectreport { get; set; }
    }
}
