//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_ERP_INVENTORY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordercontract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ordercontract()
        {
            this.plancomponentlists = new HashSet<plancomponentlist>();
        }
    
        public string ContractID { get; set; }
        public string ContractName { get; set; }
        public string UserID { get; set; }
        public string LeadingOfficial { get; set; }
        public string ContractFileAdd { get; set; }
        public string ContractRemarks { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual usermanagement usermanagement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plancomponentlist> plancomponentlists { get; set; }
    }
}
